upstream web_backend {
    server WEB1_PRIVATE_IP:80;
    server WEB2_PRIVATE_IP:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://web_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
